### PR TITLE
Copy nits

### PR DESCRIPTION
**Pull request by lukepighetti**

### CODE REVIEW

**Comment by s0kil** [comment]
@lukepighetti What does "nits" stand for? (:

**Comment by lukepighetti** [comment]
Its a polite way of saying "I just found a little thing that isn't a big deal so I don't want you to think this is a critique of your work but here it is so you can fix it if you like"

**Comment by lukepighetti** [comment]
This is ready for review.

**Comment by gdotdesign** [comment]
Appreciated :slightly_smiling_face: :+1:

**Comment by s0kil** [comment]
Slowly Mint is starting to speak English, (:

**Pull request merged**
