### PR TITLE
Mint Language added to Homebrew-alpha community.

### PR DESCRIPTION
**Pull request by Acciaiodigitale**
You can use on Mac or Linux

### CODE REVIEW

**Comment by gdotdesign** [comment]
What is `homebrew-community/alpha` ? tried to google it, but didn't find anything relevant.

**Comment by gdotdesign** [comment]
I found it I think https://github.com/homebrew-community/homebrew-alpha

**Comment by Acciaiodigitale** [comment]
Yes it's a project that I'm part of, so that the repo doesn't depends on me only

**Comment by gdotdesign** [comment]
Great :+1: Thanks

**Pull request merged**
