### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by zw963**

### CODE REVIEW

**Comment by zw963** [comment]
Hi, there is one more question for this file.

I can't find out the rule of record name.

```
record SubscriberCount.Subscription {
        update : Function(Number, Promise(Never, Void))
      }
```

So, what is the `SubscriberCount.Subscription` stand for? a nested record name? or just in mint-lang, the record name can include a dot(.)?  is constant can include `.` in it name?

Thank you.

**Comment by gdotdesign** [comment]
Thanks for the PR.

> So, what is the `SubscriberCount.Subscription` stand for? a nested record name? or just in mint-lang, the record name can include a dot(.)? is constant can include `.` in it name?

The dot(.) is basically a separator, it doesn't have any meaning other than that. Constants can include underscore `_`

**Comment by zw963** [comment]
> The dot(.) is basically a separator, it doesn't have any meaning other than that. 

Cool, maybe we should add those to document somewhere. if a record can be form SubscriberCount.Subscription, how about component or others?

> Constants can include underscore `_`

In our document here https://mint-lang.com/guide/reference/constants, no point out constant can have underscore `_`.

```
 The variable name of a constant must be in all-uppercase characters. 
```

thank you.

**Comment by Sija** [comment]
Since this PR fixes couple of typos, I'll go ahead and merge it as-is.
Please, open a new PR for further (docs) improvements, thanks! ❤️

**Pull request merged**
