### PR TITLE
Add test help output to cli guide

### PR DESCRIPTION
**Pull request by johanbrandhorst**
This would prevent such problems as I ran into
with https://github.com/mint-lang/mint/issues/168.

Fixes https://github.com/mint-lang/mint/issues/171.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
I haven't tested this locally, since the README had no instructions for how to run it. I was hoping CI might automatically deploy the changes on a branch :grin:.

**Comment by johanbrandhorst** [comment]
> It would helpful to add which values `--browser` accepts, "chrome" and "firefox".

Good idea! I added `chrome` and `firefox` to a paragraph below the help text. Do you know how to render the pages locally?

**Comment by s0kil** [comment]
> Do you know how to render the pages locally?

No idea, I'm sure it's the standard Ruby on Rails process.

**Comment by gdotdesign** [comment]
I'll try to update the README today :+1: Otherwise it looks good!

**Pull request merged**
